### ISSUE TITLE
Publish JAR to github releases for easy install?

### ISSUE THREAD

**Issue by petemounce** [GregBartlett/sonar-resharper#20]
I'm creating automation to stand up my sonarqube instance, and that requires being able to download the JAR files of plugins via curl easily - it would be really handy to be able to grab a release that way.

**Comment by GregBartlett** [comment]
@petemounce can you take a look at the releases section and let me know if that is what you are talking about heer? Please and thanks.

**Comment by petemounce** [comment]
@GregBartlett yup, looks good - thanks!
